added custom pipeline and solved exercise
Shikha2105/mle-training-mod3 pull request #2
Opened 2023-05-22 13:23 UTC by Shikha2105

solved exercise questions and created custom transfoemer.

2023-05-24 15:08 UTC, tigersharmadivyansh2000 requested changes
Make changes in housing.ipynb

2023-05-24 15:08 UTC, tigersharmadivyansh2000 commented on housing.ipynb
In cell 27, line "y_imp = preprocessing.fit(X).get_feature_names_out()", got the error as Error message

AttributeError: Estimator impute does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?

2023-05-24 15:42 UTC, Shikha2105 commented on housing.ipynb
![image](https://github.com/Shikha2105/mle-training-mod3/assets/105652246/cc7961a0-35e8-4eaf-8336-2e6177bbdf1c)
I have ran that cell and it is working fine for me . Please run all cells in sequential manner .

2023-05-24 17:48 UTC, tigersharmadivyansh2000 commented on housing.ipynb
Run all, runs the notebook in sequential manner only. I was able to run after removing the some values in param grid
![image](https://github.com/Shikha2105/mle-training-mod3/assets/111710640/fe929ef6-225e-4269-b346-1ef4f877ed19)

2023-05-25 12:07 UTC, tigersharmadivyansh2000 approved these changes
Looks good

2023-05-25 12:08 UTC, merged